export const copy = {
  en: {
    brand: "Pizza Geek",
    title: "Dough Calculator",
    subtitle:
      "Style-aware dough math for serious home and pro pizza making, with clearer planning, better bake guidance, and a much stronger recipe workflow.",
    subtitleBread:
      "Bread-first dough planning for focaccia, flatbread, and loaf workflows, with proofing and bake guidance that tracks the product.",
    resetStyle: "Reset style",
    resetProfile: "Reset profile",
    printRecipe: "Print sheet",
    buySlice: "Buy a slice",
    settings: "Settings",
    theme: "Theme",
    language: "Language",
    productMode: "Product",
    workspaceMode: "Workspace",
    temperatureUnit: "Temperature",
    sizeUnit: "Length unit",
    english: "English",
    german: "Deutsch",
    italian: "Italiano",
    pizzaProduct: "Pizza",
    breadProduct: "Bread",
    guidedMode: "Guided",
    studioMode: "Studio",
    variants: "Variants",
    dark: "Dark",
    light: "Light",
    fahrenheit: "Fahrenheit",
    celsius: "Celsius",
    styles: "Styles",
    doughSetup: "Dough Setup",
    fermentation: "Fermentation",
    doughStudio: "Preferment / Final Dough & Flour",
    bakeSurface: "Shape & Bake",
    ovenProfile: "Oven Profile",
    planner: "Plan Ahead",
    formula: "Recipe Sheet",
    processTimeline: "Process timeline",
    processTimelineHint: "See the live dough flow, waiting stages, and the next hands-on checkpoint.",
    currentStage: "Current stage",
    nextStage: "Next stage",
    noCurrentStage: "Not started yet",
    noNextStage: "No later step",
    prefermentWindow: "Preferment window",
    prefermentMixAt: "Mix",
    prefermentReadyFrom: "Ready from",
    prefermentBestWindow: "Best window",
    prefermentUseBy: "Use by",
    plannerTimelineNotes: "Planner notes",
    plannerNoteAdd: "Add baker note",
    plannerNoteShow: "Show",
    plannerNoteHide: "Hide",
    plannerNote: "Baker note",
    plannerNotePlaceholder: "Add a reminder, observation, or handoff for this step.",
    plannerMarkDone: "Done",
    plannerSkipStep: "Skip",
    plannerClearStepState: "Clear",
    plannerStepDone: "Checked off",
    plannerStepSkipped: "Skipped",
    recipeHealth: "Quality Readout",
    guidance: "Bake Guidance",
    method: "Method",
    cost: "Costing",
    savedRecipes: "Recipe Library",
    bakeJournal: "Bake Journal",
    doughBalls: "Dough balls",
    ballWeight: "Ball weight",
    pieces: "Pieces",
    pieceWeight: "Piece weight",
    loaves: "Loaves",
    loafWeight: "Loaf weight",
    hydration: "Hydration",
    salt: "Salt",
    oil: "Oil",
    sugar: "Sugar",
    honey: "Honey",
    malt: "Malt",
    lard: "Lard",
    milkPowder: "Milk powder",
    yeastType: "Yeast",
    naturalStarter: "Natural starter",
    mixerType: "Mixer",
    manualYeast: "Manual yeast",
    flourTemp: "Flour temp",
    roomBulk: "Room bulk",
    cellarTime: "Cellar",
    coldBulk: "Fridge bulk",
    coldBall: "Fridge ball",
    finalRise: "Final rise",
    roomTemp: "Room temp",
    cellarTemp: "Cellar temp",
    fridgeTemp: "Fridge temp",
    roomHumidity: "Room humidity",
    cellarHumidity: "Cellar humidity",
    fridgeHumidity: "Fridge humidity",
    prefermentMode: "Preferment style",
    none: "None",
    poolish: "Poolish",
    biga: "Biga",
    tiga: "Tiga",
    bassinage: "Bassinage",
    "lievito-madre": "Lievito madre",
    sauerdough: "Sourdough",
    prefermentFlour: "Preferment flour",
    bigaHydration: "Biga hydration",
    starterInoculation: "Starter inoculation",
    prefermentRoom: "Preferment room",
    prefermentCold: "Preferment cold",
    flourBlend: "Flour blend",
    addFlour: "Add flour",
    filterFlours: "Filter flours",
    filterFloursPlaceholder: "Search by brand, flour, type, or W strength",
    flourFilterEmpty: "No flours match that filter yet.",
    customFlour: "Custom flour",
    customFlourHint: "Add your own flour values here so the blend strength and hydration guidance use your bag correctly.",
    customFlourBrand: "Custom flour brand",
    customFlourName: "Custom flour name",
    customFlourType: "Custom flour type",
    customFlourProtein: "Protein",
    customFlourWStrength: "W strength",
    customFlourAbsorption: "Absorption adj.",
    addCustomFlour: "Add custom flour",
    removeCustomFlour: "Remove custom flour",
    blendTotal: "Blend total",
    totalLabel: "total",
    styleLibrary: "Full style library",
    breadProfiles: "Bread profiles",
    breadModeHint: "Bread mode covers pan breads, flatbreads, and loaf profiles with bread-specific proofing and bake guidance.",
    productModeHint: "Pizza keeps the full pizza style library. Bread narrows the app to bread-first profiles instead of pizza assumptions.",
    workspaceHint: "Guided keeps the essentials up front. Switch to Studio for flour blending, costing, saves, and bake logging.",
    guidedStylesHint: "Start with a core style, then use the full library for regional or specialty doughs.",
    prefermentHint:
      "Bassinage is a mixing technique, not a preferment. Lievito madre and sourdough use the preferment slot here. Leave manual yeast blank for starter-only doughs, or add a manual yeast % for hybrid leavening.",
    appInstall: "App install",
    appInstallHint: "Install Pizza Geek for faster launch and offline recipe access.",
    installApp: "Install app",
    installReady: "Ready to install on this device.",
    installedApp: "Installed and launchable like an app.",
    installUnavailable: "Installation is not available in this browser yet.",
    offlineReady: "Offline cache is ready after your first visit.",
    offlinePending: "Offline support is preparing.",
    offlineNow: "You are offline. Cached app screens should still work.",
    recipeData: "Recipe data",
    recipeDataHint: "Move saved recipes and bake journal entries between devices with a versioned JSON backup.",
    panGeometry: "Pan geometry",
    quickWeights: "Quick size weights",
    sizeHint: "Tap a diameter to apply a typical dough-ball weight for this style.",
    freeformLoafHint: "Freeform loaves skip pizza size presets. Shape tight, proof in a banneton or lined bowl, then score and steam the bake.",
    tinLoafHint: "Tin loaves use the pan dimensions above to estimate dough weight and keep the bake profile honest.",
    shape: "Shape",
    unit: "Unit",
    rectangular: "Rectangular",
    round: "Round",
    inches: "Inches",
    centimeters: "Centimeters",
    length: "Length",
    width: "Width",
    diameter: "Diameter",
    depth: "Depth",
    applyPanWeight: "Apply pan weight",
    stoneTemp: "Stone temp",
    topHeat: "Top heat",
    deckTemp: "Deck temp",
    broilerFinish: "Broiler finish",
    finishingBroil: "Finishing broil",
    sauce: "Sauce",
    sauceStyle: "Sauce style",
    sauceWeight: "Sauce / pizza",
    sauceHint: "Adds sauce guidance to the recipe sheet and method.",
    sauceClassic: "Classic tomato",
    sauceRaw: "Raw tomato",
    sauceCooked: "Cooked tomato",
    sauceWhite: "White sauce",
    today: "Starting now",
    readyBy: "Ready by",
    readyDate: "Ready date",
    quickSchedule: "Quick schedule",
    quickScheduleHint: "Pick a bake target and Pizza Geek back-plans the mix for you.",
    breadQuickScheduleHint: "Pick a loaf window and Pizza Geek back-plans bulk, proof, and bake around the bread profile.",
    startAt: "Start",
    todayTarget: "Same Day",
    overnightTarget: "Overnight",
    twoDayTarget: "2-Day",
    threeDayTarget: "3-Day",
    rapidTarget: "Rapid",
    breadExpressTarget: "Mix & Bake",
    breadTodayTarget: "Same-Day Loaf",
    breadOvernightTarget: "Next Morning",
    breadTwoDayTarget: "Slow Flavor",
    breadThreeDayTarget: "Weekend Loaf",
    flour: "Flour",
    water: "Water",
    yeast: "Yeast",
    bake: "Bake",
    effectiveFerment: "Effective ferment",
    totalTime: "Total time",
    waterTemp: "Water temp",
    targetFdt: "Target FDT",
    bakeTime: "Bake time",
    prefermentSplit: "Preferment split",
    mainDough: "Main dough",
    inPreferment: "in preferment",
    mainDoughAdditions: "Main dough additions",
    additionalFlour: "additional flour",
    additionalWater: "additional water",
    additionalYeast: "additional yeast",
    batch: "Batch",
    perDough: "Per dough",
    perPiece: "Per piece",
    perLoaf: "Per loaf",
    recipeName: "Recipe name",
    save: "Save",
    print: "Print",
    export: "Export",
    exportData: "Export data",
    importData: "Import data",
    copy: "Copy",
    dataExported: "Recipe backup downloaded.",
    dataExportError: "Couldn't download the backup.",
    dataImportError: "Couldn't import that file. Use a Pizza Geek backup JSON.",
    addPhoto: "Add photo",
    removePhoto: "Remove photo",
    rating: "Rating",
    outcome: "Outcome",
    notes: "Notes",
    notesPlaceholder:
      "What happened during the bake? Crumb, color, shaping, oven behavior, next adjustment...",
    logBake: "Log bake",
    keeper: "Keeper",
    tweak: "Tweak",
    fail: "Fail",
    savedCount: "saved recipes",
    journalCount: "journal entries",
    noPhoto: "No photo yet",
    flourCost: "Flour / kg",
    yeastCost: "Yeast / kg",
    oilCost: "Oil / kg",
    currency: "Currency",
    hydrationFit: "Hydration fit",
    saltBalance: "Salt balance",
    fermentPlan: "Ferment plan",
    flourStrength: "Flour strength",
    mixTemperature: "Mix temperature",
    advancedSchedule: "Detailed schedule",
    sauceRecipeDetails: "Sauce recipe",
    collapseSection: "Collapse section",
    expandSection: "Expand section"
  },
  de: {
    brand: "Pizza Geek",
    title: "Teigrechner",
    subtitle:
      "Stilbewusste Teigberechnung für ambitionierte Home- und Profi-Pizza, mit klarerer Planung, besserer Backführung und einem deutlich stärkeren Rezept-Workflow.",
    subtitleBread:
      "Brotorientierte Teigplanung für Focaccia-, Fladenbrot- und Laib-Workflows, mit Gare- und Backhinweisen passend zum Produkt.",
    resetStyle: "Stil zurücksetzen",
    resetProfile: "Profil zurücksetzen",
    printRecipe: "Rezept drucken",
    buySlice: "Pizza spendieren",
    settings: "Einstellungen",
    theme: "Thema",
    language: "Sprache",
    productMode: "Produkt",
    workspaceMode: "Arbeitsmodus",
    temperatureUnit: "Temperatur",
    sizeUnit: "Längeneinheit",
    english: "Englisch",
    german: "Deutsch",
    italian: "Italiano",
    pizzaProduct: "Pizza",
    breadProduct: "Brot",
    guidedMode: "Geführt",
    studioMode: "Studio",
    variants: "Varianten",
    dark: "Dunkel",
    light: "Hell",
    fahrenheit: "Fahrenheit",
    celsius: "Celsius",
    styles: "Stile",
    doughSetup: "Teig-Setup",
    fermentation: "Gare",
    doughStudio: "Vorteig / Hauptteig & Mehl",
    bakeSurface: "Form & Backen",
    ovenProfile: "Ofenprofil",
    planner: "Backplanung",
    formula: "Rezeptblatt",
    processTimeline: "Prozess-Timeline",
    processTimelineHint: "Zeigt den aktuellen Teigablauf, Wartephasen und den nächsten Handgriff.",
    currentStage: "Aktuelle Phase",
    nextStage: "Nächste Phase",
    noCurrentStage: "Noch nicht gestartet",
    noNextStage: "Kein späterer Schritt",
    prefermentWindow: "Vorteig-Fenster",
    prefermentMixAt: "Ansetzen",
    prefermentReadyFrom: "Reif ab",
    prefermentBestWindow: "Bestes Fenster",
    prefermentUseBy: "Spätestens nutzen",
    plannerTimelineNotes: "Planer-Notizen",
    plannerNoteAdd: "Bäcker-Notiz hinzufügen",
    plannerNoteShow: "Öffnen",
    plannerNoteHide: "Schließen",
    plannerNote: "Bäcker-Notiz",
    plannerNotePlaceholder: "Merke dir hier Erinnerung, Beobachtung oder Übergabe für diesen Schritt.",
    plannerMarkDone: "Erledigt",
    plannerSkipStep: "Überspringen",
    plannerClearStepState: "Zurücksetzen",
    plannerStepDone: "Abgehakt",
    plannerStepSkipped: "Übersprungen",
    recipeHealth: "Qualitätscheck",
    guidance: "Hinweise",
    method: "Ablauf",
    cost: "Zutatenkosten",
    savedRecipes: "Rezeptbibliothek",
    bakeJournal: "Backjournal",
    doughBalls: "Teiglinge",
    ballWeight: "Teiglingsgewicht",
    pieces: "Stücke",
    pieceWeight: "Stückgewicht",
    loaves: "Laibe",
    loafWeight: "Laibgewicht",
    hydration: "Hydration",
    salt: "Salz",
    oil: "Öl",
    sugar: "Zucker",
    honey: "Honig",
    malt: "Malz",
    lard: "Schmalz",
    milkPowder: "Milchpulver",
    yeastType: "Hefe",
    naturalStarter: "Natürlicher Starter",
    mixerType: "Mischer",
    manualYeast: "Manuelle Hefe",
    flourTemp: "Mehltemp.",
    roomBulk: "Raumgare",
    cellarTime: "Kellergare",
    coldBulk: "Kühl-Stockgare",
    coldBall: "Kühl-Stückgare",
    finalRise: "Endgare",
    roomTemp: "Raumtemp.",
    cellarTemp: "Kellertemp.",
    fridgeTemp: "Kühlschranktemp.",
    roomHumidity: "Raumfeuchte",
    cellarHumidity: "Kellerfeuchte",
    fridgeHumidity: "Kühlschrankfeuchte",
    prefermentMode: "Vorteig-Stil",
    none: "Keiner",
    poolish: "Poolish",
    biga: "Biga",
    tiga: "Tiga",
    bassinage: "Bassinage",
    "lievito-madre": "Lievito madre",
    sauerdough: "Sauerteig",
    prefermentFlour: "Vorteig-Mehl",
    bigaHydration: "Biga-Hydration",
    starterInoculation: "Starter-Anteil",
    prefermentRoom: "Vorteig Raum",
    prefermentCold: "Vorteig kalt",
    flourBlend: "Mehlmischung",
    addFlour: "Mehl hinzufügen",
    filterFlours: "Mehle filtern",
    filterFloursPlaceholder: "Nach Marke, Mehl, Typ oder W-Wert suchen",
    flourFilterEmpty: "Kein Mehl passt zu diesem Filter.",
    customFlour: "Eigenes Mehl",
    customFlourHint: "Trage hier deine eigenen Mehlwerte ein, damit die Blend-Stärke und Hydrationshinweise korrekt berechnet werden.",
    customFlourBrand: "Marke des eigenen Mehls",
    customFlourName: "Name des eigenen Mehls",
    customFlourType: "Typ des eigenen Mehls",
    customFlourProtein: "Protein",
    customFlourWStrength: "W-Wert",
    customFlourAbsorption: "Absorptions-Korr.",
    addCustomFlour: "Eigenes Mehl hinzufügen",
    removeCustomFlour: "Eigenes Mehl entfernen",
    blendTotal: "Mischung gesamt",
    totalLabel: "gesamt",
    styleLibrary: "Komplette Stilbibliothek",
    breadProfiles: "Brotprofile",
    breadModeHint: "Der Brotmodus deckt Blechbrote, Fladenbrote und Laibprofile mit brotspezifischer Gare- und Backführung ab.",
    productModeHint: "Pizza behält die volle Pizzastil-Bibliothek. Brot richtet die App auf Brotprofile statt auf Pizza-Annahmen aus.",
    workspaceHint: "Geführt zeigt zuerst das Wesentliche. Studio öffnet Mehlmischung, Kosten, Speicher und Backjournal.",
    guidedStylesHint: "Starte mit einem Kernstil und wechsle für regionale oder spezielle Teige in die volle Bibliothek.",
    prefermentHint:
      "Bassinage ist eine Mischtechnik, kein Vorteig. Lievito madre und Sauerteig nutzen hier den Vorteig-Slot. Lasse die manuelle Hefe leer fur reine Starterteige oder trage einen Prozentwert fur Hybridteige ein.",
    appInstall: "App-Installation",
    appInstallHint: "Installiere Pizza Geek für schnelleren Start und Offline-Zugriff auf Rezepte.",
    installApp: "App installieren",
    installReady: "Auf diesem Gerät installierbar.",
    installedApp: "Installiert und wie eine App startbar.",
    installUnavailable: "Installation ist in diesem Browser derzeit nicht verfügbar.",
    offlineReady: "Offline-Cache ist nach dem ersten Besuch bereit.",
    offlinePending: "Offline-Unterstützung wird vorbereitet.",
    offlineNow: "Du bist offline. Zwischengespeicherte App-Seiten sollten weiter funktionieren.",
    recipeData: "Rezeptdaten",
    recipeDataHint: "Verschiebe gespeicherte Rezepte und Backjournal-Einträge zwischen Geräten mit einem versionierten JSON-Backup.",
    panGeometry: "Blechgeometrie",
    quickWeights: "Schnellgewichte",
    sizeHint: "Ein Durchmesser setzt ein typisches Teiggewicht für diesen Stil.",
    freeformLoafHint: "Freigeschobene Laibe nutzen keine Pizza-Größen. Straff formen, im Garkorb oder in einer ausgelegten Schüssel gehen lassen, dann einschneiden und mit Dampf backen.",
    tinLoafHint: "Kastenbrote nutzen die Formmaße oben für Gewichtsschätzung und ein ehrliches Backprofil.",
    shape: "Form",
    unit: "Einheit",
    rectangular: "Rechteckig",
    round: "Rund",
    inches: "Zoll",
    centimeters: "Zentimeter",
    length: "Länge",
    width: "Breite",
    diameter: "Durchmesser",
    depth: "Tiefe",
    applyPanWeight: "Blechgewicht übernehmen",
    stoneTemp: "Steintemp.",
    topHeat: "Oberhitze",
    deckTemp: "Decktemp.",
    broilerFinish: "Grill-Finish",
    finishingBroil: "Abschlussgrill",
    sauce: "Sauce",
    sauceStyle: "Saucenstil",
    sauceWeight: "Sauce / Pizza",
    sauceHint: "Fügt Saucenhinweise im Rezeptblatt und Ablauf hinzu.",
    sauceClassic: "Klassische Tomate",
    sauceRaw: "Rohe Tomate",
    sauceCooked: "Gekochte Tomate",
    sauceWhite: "Weisse Sauce",
    today: "Jetzt starten",
    readyBy: "Fertig bis",
    readyDate: "Fertig am",
    quickSchedule: "Schnellplanung",
    quickScheduleHint: "Wähle dein Backziel und Pizza Geek plant den Start rückwärts für dich.",
    breadQuickScheduleHint: "Wähle dein Brotfenster und Pizza Geek plant Stockgare, Endgare und Backstart passend zum Profil rückwärts.",
    startAt: "Start",
    todayTarget: "Gleicher Tag",
    overnightTarget: "Über Nacht",
    twoDayTarget: "2 Tage",
    threeDayTarget: "3 Tage",
    rapidTarget: "Schnell",
    breadExpressTarget: "Mischen & Backen",
    breadTodayTarget: "Tageslaib",
    breadOvernightTarget: "Nächster Morgen",
    breadTwoDayTarget: "Mehr Aroma",
    breadThreeDayTarget: "Wochenendlaib",
    flour: "Mehl",
    water: "Wasser",
    yeast: "Hefe",
    bake: "Backen",
    effectiveFerment: "Effektive Gare",
    totalTime: "Gesamtzeit",
    waterTemp: "Wassertemp.",
    targetFdt: "Ziel-FDT",
    bakeTime: "Backzeit",
    prefermentSplit: "Vorteig-Aufteilung",
    mainDough: "Hauptteig",
    inPreferment: "im Vorteig",
    mainDoughAdditions: "Hauptteig-Zugaben",
    additionalFlour: "zusätzliches Mehl",
    additionalWater: "zusätzliches Wasser",
    additionalYeast: "zusätzliche Hefe",
    batch: "Charge",
    perDough: "Pro Teigling",
    perPiece: "Pro Stück",
    perLoaf: "Pro Laib",
    recipeName: "Rezeptname",
    save: "Speichern",
    print: "Drucken",
    export: "Export",
    exportData: "Daten exportieren",
    importData: "Daten importieren",
    copy: "Kopieren",
    dataExported: "Rezept-Backup heruntergeladen.",
    dataExportError: "Das Backup konnte nicht heruntergeladen werden.",
    dataImportError: "Diese Datei konnte nicht importiert werden. Nutze ein Pizza-Geek-Backup als JSON.",
    addPhoto: "Foto hinzufügen",
    removePhoto: "Foto entfernen",
    rating: "Bewertung",
    outcome: "Ergebnis",
    notes: "Notizen",
    notesPlaceholder:
      "Wie lief der Backtag? Krume, Farbe, Formen, Ofenverhalten, nächste Anpassung...",
    logBake: "Backen protokollieren",
    keeper: "Bleibt so",
    tweak: "Nachscharfen",
    fail: "Fehlversuch",
    savedCount: "gespeicherte Rezepte",
    journalCount: "Journaleinträge",
    noPhoto: "Noch kein Foto",
    flourCost: "Mehl / kg",
    yeastCost: "Hefe / kg",
    oilCost: "Öl / kg",
    currency: "Währung",
    hydrationFit: "Hydration",
    saltBalance: "Salzbalance",
    fermentPlan: "Gareplan",
    flourStrength: "Mehlstärke",
    mixTemperature: "Mischtemperatur",
    advancedSchedule: "Detaillierter Zeitplan",
    sauceRecipeDetails: "Saucenrezept",
    collapseSection: "Bereich einklappen",
    expandSection: "Bereich ausklappen"
  },
  it: {
    brand: "Pizza Geek",
    title: "Calcolatore Impasti",
    subtitle:
      "Calcolo impasti orientato allo stile per una pizza fatta seriamente, con pianificazione più chiara, guida di cottura migliore e un flusso ricette più forte.",
    subtitleBread:
      "Pianificazione dell'impasto orientata al pane per focaccia, pani piatti e filoni, con guida di lievitazione e cottura che segue il prodotto.",
    resetStyle: "Reimposta stile",
    resetProfile: "Reimposta profilo",
    printRecipe: "Stampa scheda",
    buySlice: "Offrimi una fetta",
    settings: "Impostazioni",
    theme: "Tema",
    language: "Lingua",
    productMode: "Prodotto",
    workspaceMode: "Workspace",
    temperatureUnit: "Temperatura",
    sizeUnit: "Unità lunghezza",
    english: "English",
    german: "Deutsch",
    italian: "Italiano",
    pizzaProduct: "Pizza",
    breadProduct: "Pane",
    guidedMode: "Guidato",
    studioMode: "Studio",
    variants: "Varianti",
    dark: "Scuro",
    light: "Chiaro",
    fahrenheit: "Fahrenheit",
    celsius: "Celsius",
    styles: "Stili",
    doughSetup: "Setup impasto",
    fermentation: "Fermentazione",
    doughStudio: "Prefermento / Impasto finale e farina",
    bakeSurface: "Forma e cottura",
    ovenProfile: "Profilo forno",
    planner: "Pianifica",
    formula: "Scheda ricetta",
    processTimeline: "Timeline processo",
    processTimelineHint: "Mostra il flusso reale dell'impasto, le attese e il prossimo passaggio operativo.",
    currentStage: "Fase attuale",
    nextStage: "Fase successiva",
    noCurrentStage: "Non ancora iniziato",
    noNextStage: "Nessun passaggio successivo",
    prefermentWindow: "Finestra prefermento",
    prefermentMixAt: "Impasto",
    prefermentReadyFrom: "Pronto da",
    prefermentBestWindow: "Finestra migliore",
    prefermentUseBy: "Usare entro",
    plannerTimelineNotes: "Note timeline",
    plannerNoteAdd: "Aggiungi nota",
    plannerNoteShow: "Apri",
    plannerNoteHide: "Chiudi",
    plannerNote: "Nota del fornaio",
    plannerNotePlaceholder: "Aggiungi promemoria, osservazione o consegna per questo passaggio.",
    plannerMarkDone: "Fatto",
    plannerSkipStep: "Salta",
    plannerClearStepState: "Azzera",
    plannerStepDone: "Completato",
    plannerStepSkipped: "Saltato",
    recipeHealth: "Controllo qualità",
    guidance: "Guida",
    method: "Metodo",
    cost: "Costi",
    savedRecipes: "Ricette salvate",
    bakeJournal: "Diario di cottura",
    doughBalls: "Panetti",
    ballWeight: "Peso panetto",
    pieces: "Pezzi",
    pieceWeight: "Peso pezzo",
    loaves: "Pagnotte",
    loafWeight: "Peso pagnotta",
    hydration: "Idratazione",
    salt: "Sale",
    oil: "Olio",
    sugar: "Zucchero",
    honey: "Miele",
    malt: "Malto",
    lard: "Strutto",
    milkPowder: "Latte in polvere",
    yeastType: "Lievito",
    naturalStarter: "Starter naturale",
    mixerType: "Impastatrice",
    manualYeast: "Lievito manuale",
    flourTemp: "Temp. farina",
    roomBulk: "Puntata ambiente",
    cellarTime: "Cantina",
    coldBulk: "Puntata frigo",
    coldBall: "Appretto frigo",
    finalRise: "Appretto finale",
    roomTemp: "Temp. ambiente",
    cellarTemp: "Temp. cantina",
    fridgeTemp: "Temp. frigo",
    roomHumidity: "Umidità ambiente",
    cellarHumidity: "Umidità cantina",
    fridgeHumidity: "Umidità frigo",
    prefermentMode: "Stile prefermento",
    none: "Nessuno",
    poolish: "Poolish",
    biga: "Biga",
    tiga: "Tiga",
    bassinage: "Bassinage",
    "lievito-madre": "Lievito madre",
    sauerdough: "Lievito naturale",
    prefermentFlour: "Farina prefermento",
    bigaHydration: "Idratazione biga",
    starterInoculation: "Inoculo starter",
    prefermentRoom: "Prefermento ambiente",
    prefermentCold: "Prefermento freddo",
    flourBlend: "Blend farine",
    addFlour: "Aggiungi farina",
    filterFlours: "Filtra farine",
    filterFloursPlaceholder: "Cerca per marca, farina, tipo o forza W",
    flourFilterEmpty: "Nessuna farina corrisponde a questo filtro.",
    customFlour: "Farina personalizzata",
    customFlourHint: "Inserisci qui i valori della tua farina così i calcoli di forza del blend e idratazione restano corretti.",
    customFlourBrand: "Marca farina personalizzata",
    customFlourName: "Nome farina personalizzata",
    customFlourType: "Tipo farina personalizzata",
    customFlourProtein: "Proteine",
    customFlourWStrength: "Forza W",
    customFlourAbsorption: "Correzione assorb.",
    addCustomFlour: "Aggiungi farina personalizzata",
    removeCustomFlour: "Rimuovi farina personalizzata",
    blendTotal: "Blend totale",
    totalLabel: "totale",
    styleLibrary: "Libreria stili completa",
    breadProfiles: "Profili pane",
    breadModeHint: "La modalità pane copre pani in teglia, pani piatti e filoni con guida specifica per lievitazione e cottura.",
    productModeHint: "Pizza mantiene l'intera libreria stili pizza. Pane restringe l'app a profili pensati prima per il pane.",
    workspaceHint: "Guidato tiene l'essenziale in primo piano. Studio apre blend farine, costi, salvataggi e diario di cottura.",
    guidedStylesHint: "Parti da uno stile base, poi usa la libreria completa per impasti regionali o speciali.",
    prefermentHint:
      "Il bassinage è una tecnica di impasto, non un prefermento. Lievito madre e lievito naturale usano qui lo slot del prefermento. Lascia vuoto il lievito manuale per impasti solo starter oppure aggiungi una percentuale per una lievitazione ibrida.",
    appInstall: "Installazione app",
    appInstallHint: "Installa Pizza Geek per un avvio più rapido e accesso offline alle ricette.",
    installApp: "Installa app",
    installReady: "Pronta da installare su questo dispositivo.",
    installedApp: "Installata e avviabile come app.",
    installUnavailable: "L'installazione non è ancora disponibile in questo browser.",
    offlineReady: "La cache offline è pronta dopo la prima visita.",
    offlinePending: "Il supporto offline si sta preparando.",
    offlineNow: "Sei offline. Le schermate in cache dovrebbero comunque funzionare.",
    recipeData: "Dati ricette",
    recipeDataHint: "Sposta ricette salvate e note di cottura tra dispositivi con un backup JSON versionato.",
    panGeometry: "Geometria teglia",
    quickWeights: "Pesi rapidi",
    sizeHint: "Tocca un diametro per applicare un peso panetto tipico per questo stile.",
    freeformLoafHint: "I filoni liberi saltano i preset pizza. Forma bene, lievita in banneton o in una ciotola rivestita, poi incidi e cuoci con vapore.",
    tinLoafHint: "I pani in stampo usano le dimensioni sopra per stimare il peso impasto e tenere onesto il profilo di cottura.",
    shape: "Forma",
    unit: "Unità",
    rectangular: "Rettangolare",
    round: "Rotonda",
    inches: "Pollici",
    centimeters: "Centimetri",
    length: "Lunghezza",
    width: "Larghezza",
    diameter: "Diametro",
    depth: "Profondità",
    applyPanWeight: "Applica peso teglia",
    stoneTemp: "Temp. pietra",
    topHeat: "Calore superiore",
    deckTemp: "Temp. platea",
    broilerFinish: "Finitura grill",
    finishingBroil: "Grill finale",
    sauce: "Salsa",
    sauceStyle: "Stile salsa",
    sauceWeight: "Salsa / pizza",
    sauceHint: "Aggiunge indicazioni salsa alla scheda ricetta e al metodo.",
    sauceClassic: "Pomodoro classico",
    sauceRaw: "Pomodoro crudo",
    sauceCooked: "Pomodoro cotto",
    sauceWhite: "Salsa bianca",
    today: "Parti ora",
    readyBy: "Pronta per",
    readyDate: "Data pronta",
    quickSchedule: "Pianificazione rapida",
    quickScheduleHint: "Scegli l'obiettivo di cottura e Pizza Geek pianifica a ritroso per te.",
    breadQuickScheduleHint: "Scegli la finestra del pane e Pizza Geek pianifica puntata, appretto e cottura in base al profilo.",
    startAt: "Inizio",
    todayTarget: "Stesso giorno",
    overnightTarget: "Notte",
    twoDayTarget: "2 giorni",
    threeDayTarget: "3 giorni",
    rapidTarget: "Rapido",
    breadExpressTarget: "Impasta e cuoci",
    breadTodayTarget: "Pane in giornata",
    breadOvernightTarget: "Domani mattina",
    breadTwoDayTarget: "Più aroma",
    breadThreeDayTarget: "Pane del weekend",
    flour: "Farina",
    water: "Acqua",
    yeast: "Lievito",
    bake: "Cottura",
    effectiveFerment: "Fermentazione effettiva",
    totalTime: "Tempo totale",
    waterTemp: "Temp. acqua",
    targetFdt: "FDT target",
    bakeTime: "Tempo cottura",
    prefermentSplit: "Divisione prefermento",
    mainDough: "Impasto finale",
    inPreferment: "nel prefermento",
    mainDoughAdditions: "Aggiunte impasto finale",
    additionalFlour: "farina aggiuntiva",
    additionalWater: "acqua aggiuntiva",
    additionalYeast: "lievito aggiuntivo",
    batch: "Batch",
    perDough: "Per panetto",
    perPiece: "Per pezzo",
    perLoaf: "Per pagnotta",
    recipeName: "Nome ricetta",
    save: "Salva",
    print: "Stampa",
    export: "Esporta",
    exportData: "Esporta dati",
    importData: "Importa dati",
    copy: "Copia",
    dataExported: "Backup ricette scaricato.",
    dataExportError: "Impossibile scaricare il backup.",
    dataImportError: "Impossibile importare questo file. Usa un backup JSON di Pizza Geek.",
    addPhoto: "Aggiungi foto",
    removePhoto: "Rimuovi foto",
    rating: "Valutazione",
    outcome: "Esito",
    notes: "Note",
    notesPlaceholder: "Com'è andata la cottura? Mollica, colore, formatura, comportamento del forno, prossima correzione...",
    logBake: "Registra cottura",
    keeper: "Da tenere",
    tweak: "Da ritoccare",
    fail: "Fallita",
    savedCount: "ricette salvate",
    journalCount: "note di cottura",
    noPhoto: "Nessuna foto",
    flourCost: "Farina / kg",
    yeastCost: "Lievito / kg",
    oilCost: "Olio / kg",
    currency: "Valuta",
    hydrationFit: "Idratazione",
    saltBalance: "Bilanciamento sale",
    fermentPlan: "Piano fermentazione",
    flourStrength: "Forza farina",
    mixTemperature: "Temperatura impasto",
    advancedSchedule: "Piano dettagliato",
    sauceRecipeDetails: "Ricetta salsa",
    collapseSection: "Comprimi sezione",
    expandSection: "Espandi sezione"
  }
} as const;

export type CopyText = Record<keyof typeof copy.en, string>;
